# Generated by Django 4.2.4 on 2023-08-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True, verbose_name='Уникальный идентификатор в телеграм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Данные пользователя телеграм бота',
                'verbose_name_plural': 'Данные пользователя телеграм бота',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userText', models.TextField(max_length=1000000, verbose_name='Текст пользователя телеграм бота')),
                ('systemText', models.TextField(max_length=1000000, verbose_name='Текст системы телеграм бота')),
                ('assistantText', models.TextField(max_length=1000000, verbose_name='Текст асистента телеграм бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_text', to='bot.userid', verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'Переписка',
                'verbose_name_plural': 'Переписка',
                'ordering': ['user_id'],
            },
        ),
    ]
