# Generated by Django 4.2.4 on 2023-08-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetext',
            name='systemText',
        ),
    ]
