# Generated by Django 4.2.4 on 2023-08-16 04:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_messagetext_systemtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTextModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Задача телеграм бота',
                'verbose_name_plural': 'Задачи телеграм бота',
                'ordering': ['id'],
            },
        ),
    ]
