# Generated by Django 4.2.4 on 2023-08-16 08:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_systemtextmodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtextmodal',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
